//Error / Exception handling

try{
    console.llog("Hello Basify");
    // throw 1;
}
catch(err){
    console.log("Throw is called");
}

finally{
    console.log("This is finally block");
}